// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HackerNewsAPI.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Item
    {
        /// <summary>
        /// Initializes a new instance of the Item class.
        /// </summary>
        public Item() { }

        /// <summary>
        /// Initializes a new instance of the Item class.
        /// </summary>
        public Item(int? id = default(int?), string deleted = default(string), string type = default(string), string by = default(string), DateTime? time = default(DateTime?), string text = default(string), string dead = default(string), int? parent = default(int?), int? poll = default(int?), IList<int?> kids = default(IList<int?>), string uRL = default(string), int? score = default(int?), string title = default(string), IList<int?> parts = default(IList<int?>), int? descendants = default(int?))
        {
            ID = id;
            Deleted = deleted;
            Type = type;
            By = by;
            Time = time;
            Text = text;
            Dead = dead;
            Parent = parent;
            Poll = poll;
            Kids = kids;
            URL = uRL;
            Score = score;
            Title = title;
            Parts = parts;
            Descendants = descendants;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ID")]
        public int? ID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Deleted")]
        public string Deleted { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "By")]
        public string By { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Time")]
        public DateTime? Time { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Text")]
        public string Text { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Dead")]
        public string Dead { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Parent")]
        public int? Parent { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Poll")]
        public int? Poll { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Kids")]
        public IList<int?> Kids { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "URL")]
        public string URL { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Score")]
        public int? Score { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Parts")]
        public IList<int?> Parts { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Descendants")]
        public int? Descendants { get; set; }

    }
}
