// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HackerNewsWeb.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class BestStoryInfo
    {
        /// <summary>
        /// Initializes a new instance of the BestStoryInfo class.
        /// </summary>
        public BestStoryInfo() { }

        /// <summary>
        /// Initializes a new instance of the BestStoryInfo class.
        /// </summary>
        public BestStoryInfo(int? id = default(int?), string by = default(string), string title = default(string))
        {
            Id = id;
            By = by;
            Title = title;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "By")]
        public string By { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Title")]
        public string Title { get; set; }

    }
}
